import {
    grayDark,
    mauveDark,
    slateDark,
    sageDark,
    oliveDark,
    sandDark,
    tomatoDark,
    redDark,
    crimsonDark,
    pinkDark,
    plumDark,
    purpleDark,
    violetDark,
    indigoDark,
    blueDark,
    skyDark,
    mintDark,
    cyanDark,
    tealDark,
    greenDark,
    grassDark,
    limeDark,
    yellowDark,
    amberDark,
    orangeDark,
    brownDark,
    bronzeDark,
    goldDark,
    grayDarkA,
    mauveDarkA,
    slateDarkA,
    sageDarkA,
    oliveDarkA,
    sandDarkA,
    tomatoDarkA,
    redDarkA,
    crimsonDarkA,
    pinkDarkA,
    plumDarkA,
    purpleDarkA,
    violetDarkA,
    indigoDarkA,
    blueDarkA,
    skyDarkA,
    mintDarkA,
    cyanDarkA,
    tealDarkA,
    greenDarkA,
    grassDarkA,
    limeDarkA,
    yellowDarkA,
    amberDarkA,
    orangeDarkA,
    brownDarkA,
    bronzeDarkA,
    goldDarkA,
} from '@radix-ui/colors';

export default {
    colors: {
        ...grayDark,
        ...mauveDark,
        ...slateDark,
        ...sageDark,
        ...oliveDark,
        ...sandDark,
        ...tomatoDark,
        ...redDark,
        ...crimsonDark,
        ...pinkDark,
        ...plumDark,
        ...purpleDark,
        ...violetDark,
        ...indigoDark,
        ...blueDark,
        ...skyDark,
        ...mintDark,
        ...cyanDark,
        ...tealDark,
        ...greenDark,
        ...grassDark,
        ...limeDark,
        ...yellowDark,
        ...amberDark,
        ...orangeDark,
        ...brownDark,
        ...bronzeDark,
        ...goldDark,

        ...grayDarkA,
        ...mauveDarkA,
        ...slateDarkA,
        ...sageDarkA,
        ...oliveDarkA,
        ...sandDarkA,
        ...tomatoDarkA,
        ...redDarkA,
        ...crimsonDarkA,
        ...pinkDarkA,
        ...plumDarkA,
        ...purpleDarkA,
        ...violetDarkA,
        ...indigoDarkA,
        ...blueDarkA,
        ...skyDarkA,
        ...mintDarkA,
        ...cyanDarkA,
        ...tealDarkA,
        ...greenDarkA,
        ...grassDarkA,
        ...limeDarkA,
        ...yellowDarkA,
        ...amberDarkA,
        ...orangeDarkA,
        ...brownDarkA,
        ...bronzeDarkA,
        ...goldDarkA,

        accent1: '$amber1',
        accent2: '$amber2',
        accent3: '$amber3',
        accent4: '$amber4',
        accent5: '$amber5',
        accent6: '$amber6',
        accent7: '$amber7',
        accent8: '$amber8',
        accent9: '$amber9',
        accent10: '$amber10',
        accent11: '$amber11',
        accent12: '$amber12',

        neutral1: '$slate1',
        neutral2: '$slate2',
        neutral3: '$slate3',
        neutral4: '$slate4',
        neutral5: '$slate5',
        neutral6: '$slate6',
        neutral7: '$slate7',
        neutral8: '$slate8',
        neutral9: '$slate9',
        neutral10: '$slate10',
        neutral11: '$slate11',
        neutral12: '$slate12',

        danger1: '$tomato1',
        danger2: '$tomato2',
        danger3: '$tomato3',
        danger4: '$tomato4',
        danger5: '$tomato5',
        danger6: '$tomato6',
        danger7: '$tomato7',
        danger8: '$tomato8',
        danger9: '$tomato9',
        danger10: '$tomato10',
        danger11: '$tomato11',
        danger12: '$tomato12',

        card1: '$slate1',
        card2: '$slate2',
        card3: '$slate3',
        card4: '$slate4',

        hiContrast: '$slate12',
        loContrast: '$slate1',
    },
    shadows: {
        xs: '-4px 0 15px rgb(0 0 0 / 50%)',
        sm: '0 5px 20px -5px rgba(20, 20, 20, 0.1)',
        md: '0 8px 30px rgba(20, 20, 20, 0.15)',
        lg: '0 30px 60px rgba(20, 20, 20, 0.15)',
        xl: '0 40px 80px rgba(20, 20, 20, 0.25)',
    },
};
