export default {
    colors: {
        accent1: '$amber1',
        accent2: '$amber2',
        accent3: '$amber3',
        accent4: '$amber4',
        accent5: '$amber5',
        accent6: '$amber6',
        accent7: '$amber7',
        accent8: '$amber8',
        accent9: '$amber9',
        accent10: '$amber10',
        accent11: '$amber11',
        accent12: '$amber12',

        neutral1: '$slate1',
        neutral2: '$slate2',
        neutral3: '$slate3',
        neutral4: '$slate4',
        neutral5: '$slate5',
        neutral6: '$slate6',
        neutral7: '$slate7',
        neutral8: '$slate8',
        neutral9: '$slate9',
        neutral10: '$slate10',
        neutral11: '$slate11',
        neutral12: '$slate12',

        neutralA1: '$slateA1',
        neutralA2: '$slateA2',
        neutralA3: '$slateA3',
        neutralA4: '$slateA4',
        neutralA5: '$slateA5',
        neutralA6: '$slateA6',
        neutralA7: '$slateA7',
        neutralA8: '$slateA8',
        neutralA9: '$slateA9',
        neutralA10: '$slateA10',
        neutralA11: '$slateA11',
        neutralA12: '$slateA12',

        danger1: '$tomato1',
        danger2: '$tomato2',
        danger3: '$tomato3',
        danger4: '$tomato4',
        danger5: '$tomato5',
        danger6: '$tomato6',
        danger7: '$tomato7',
        danger8: '$tomato8',
        danger9: '$tomato9',
        danger10: '$tomato10',
        danger11: '$tomato11',
        danger12: '$tomato12',

        card1: '$slate1',
        card2: '$slate2',
        card3: '$slate3',
        card4: '$slate4',

        hiContrast: '$slate12',
        loContrast: 'white',
    },
    shadows: {
        xs: '-4px 0 4px rgb(0 0 0 / 5%);',
        sm: '0 5px 20px -5px rgba(0, 0, 0, 0.1)',
        md: '0 8px 30px rgba(0, 0, 0, 0.15)',
        lg: '0 30px 60px rgba(0, 0, 0, 0.15)',
        xl: '0 40px 80px rgba(0, 0, 0, 0.25)',
    },
};
